    <div id="page-preloader" class="backdrop">
        <div class="dot-loader">
            <div class="item-1"></div>
            <div class="item-2"></div>
            <div class="item-3"></div>
            <div class="item-4"></div>
            <div class="item-5"></div>
        </div>
    </div>

    <header class="header">
        <div class="wrap">
            <a href="/" class="logo wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="1s"><img src="/img/logo.png"
                    alt="Optimo"></a>
            <nav class="menu">
                <ul class="menu__list">
                    <li class="menu__item wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="0.9s"><a
                            href="#">Услуги</a></li>
                    <li class="menu__item wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="0.8s"><a
                            href="#">Работы</a></li>
                    <li class="menu__item wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="0.7s"><a
                            href="#">Отзывы</a></li>
                    <li class="menu__item wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="0.6s"><a
                            href="#">Контакты</a></li>
                </ul>
                <a href="#" class="drop-menu wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="0.5s"><img
                        src="/img/menu.png" alt="кнопка меню"></a>
            </nav>
            <a href="tel:+74232060353" class="phone wow fadeInLeft" data-wow-duration="0.8s"
                data-wow-delay="0.4s">+7(423)<span>206 0353</span></a>
            <a href="#" class="calculate-order wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="0.3s">Расcчитать
                заказ</a>
            <a href="#" class="pay-order wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="0.2s">Оплатить
                заказ</a>
        </div>
    </header>
    <main class="main">
        <section class="title__section">
            <div class="wrap">
                <div class="">
                    <h1 class="title wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.3s">Контекстная реклама
                    </h1>
                    <h3 class="subtitle wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.5s">эффективно,
                        измеримо, быстро!</h3>
                    <p class="description wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.7s">
                        Если вас заинтересовала наша страница о контекстной рекламе – значит, что вы либо уже имели опыт
                        настройки контекстной рекламы и, скорее всего, результаты не оправдали ожиданий, либо только
                        задумываетесь о ее внедрении в инструменты продвижения компании. Здесь мы разберем что вообще
                        такое
                        контекстная реклама, почему на сегодняшний день она так востребована и как мы ее делаем в
                        Optimo.
                    </p>
                    <a href="#" class="order wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.9s"><span
                            class="order-helper"></span> заказать</a>
                </div>
            </div>
        </section>
        <section class="what-contextual-advertising">
            <div class="wrap bg-light-gray">
                <div class="">
                    <h2 class="title wow bounceInRight" data-wow-duration="0.8s" data-wow-delay="0.2s">Что такое
                        <span>контекстная реклама</span></h2>
                    <div class="description wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="0.6s">
                        <p>
                            <span>Контекстная реклама</span> – отрасль интернет-рекламы, которая показывается в
                            поисковой выдаче
                            в
                            виде текстового объявления и на сайте в виде баннера
                            или видео.

                        </p>
                        <p>
                            Поисковая реклама демонстрируется среди результатов поиска на ту же тематику и содержит
                            гиперссылки на сайт рекламодателя.

                        </p>
                    </div>
                </div>
            </div>
            <div class="wrap">
                <div class="wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.6s">
                    <p>
                        Медийная реклама показывается на страницах сайтов и в мобильных приложениях, входящих в
                        рекламную сеть Яндекс (РСЯ) или контекстно-медийную сеть Google (КМС). Отображается только у
                        тех
                        пользователей, которые ранее делали запрос в интернете на такую же или похожую тематику.
                        Может
                        не содержать гиперссылки, если реклама имиджевая.
                    </p>
                    <p>
                        <span>
                            Контекстная реклама не только оказывает целенаправленное воздействие на потенциального
                            клиента,
                            но и позволяет в точности выявить целевую аудиторию, а так же проанализировать действия,
                            которые
                            совершают пользователи на сайте рекламодателя. На сегодняшний день является одним из
                            наиболее
                            эффективных инструментов продвижения.
                        </span>
                    </p>
                </div>
            </div>
        </section>
        <section class="how-we-doing">
            <div class="wrap">
                <h2 class="title wow bounceInRight" data-wow-duration="0.8s" data-wow-delay="0.3s">Как мы делаем
                    контекстную
                    рекламу</h2>
                <ul class="how-we-doing__list">
                    <li class="how-we-doing__item wow fadeInRight" data-wow-duration="0.2s" data-wow-delay="0.2s">
                        Собираем, прорабатываем
                        и разгруппировываем
                        семантическое ядро
                    </li>
                    <li class="how-we-doing__item wow fadeInRight" data-wow-duration="0.2s" data-wow-delay="0.3s">
                        Выявляем минус-слова на каждую группу объявлений
                    </li>
                    <li class="how-we-doing__item wow fadeInRight" data-wow-duration="0.2s" data-wow-delay="0.4s">
                        Создаем разные рекламные кампании по регионам, целям и видам рекламы
                    </li>
                    <li class="how-we-doing__item wow fadeInRight" data-wow-duration="0.2s" data-wow-delay="0.5s">
                        Настраиваем геотаргетинг и временной таргетинг для каждой кампании
                    </li>
                    <li class="how-we-doing__item wow fadeInRight" data-wow-duration="0.2s" data-wow-delay="0.6s">
                        Разделяем кампанию на группы объявлений по тематикам в РСЯ и КМС, по ключевым словам на
                        поиске
                    </li>
                    <li class="how-we-doing__item wow fadeInRight" data-wow-duration="0.2s" data-wow-delay="0.7s">
                        В каждой группе создаем от 3 объявлений для проведения A/B тестирования в РСЯ и КМС
                    </li>
                    <li class="how-we-doing__item wow fadeInRight" data-wow-duration="0.2s" data-wow-delay="0.8s">
                        Составляем продающие заголовки для каждого объявления
                    </li>
                    <li class="how-we-doing__item wow fadeInRight" data-wow-duration="0.2s" data-wow-delay="0.9s">
                        Формируем УТП компании с помощью быстрых ссылок и уточнений на поиске
                    </li>
                    <li class="how-we-doing__item wow fadeInRight" data-wow-duration="0.2s" data-wow-delay="1s">
                        Объявления размечаем UTM-метками для отслеживания статистики по переходам
                    </li>
                    <li class="how-we-doing__item wow fadeInRight" data-wow-duration="0.2s" data-wow-delay="1.1s">
                        Настраиваем цели для каждой рекламной кампании и отслеживаем конверсию
                    </li>
                </ul>
            </div>
        </section>
        <section class="test">
            <div class="wrap">
                <div class="yandex wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="0.7s"><img
                        src="/img/socialprev.png" alt="Яндекс метрика"></div>
                <div class="google wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="0.5s"><img
                        src="/img/logo_lockup_analytics_icon_horizontal_black_2x.png" alt="Google Analytics"></div>
                <p class="wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="0.2s">
                    Мы уже упомянули ранее, что настройка рекламной кампании – это только пол дела на пути к
                    получению целевого трафика. Теперь ее нужно регулярно отслеживать и проводить анализ
                    эффективности. Тут мы, конечно же, не обходимся без систем аналитики Яндекс.Метрика и Google
                    Analytics, но и не ограничиваемся ими.
                </p>
            </div>
        </section>
        <section class=" how-we-doing__slider">
            <div class="wrap">
                <h2 class="title title_gray wow bounceInRight" data-wow-duration="0.8s" data-wow-delay="0.3s">Как мы
                    не делаем </h2>
                <div class="slider__wrap wow fadeInUp" data-wow-duration="0.8s" data-wow-delay="0.3s">
                    <ul class="slider__list">
                        <li class="slider__item">
                            Мы не разбрасываемся деньгами наших клиентов, а относимся к ним как к собственным,
                            поэтому
                            заранее просчитываем приблизительный бюджет на рекламную кампанию. Выстраиваем
                            прозрачные
                            отношения с заказчиками и не скрываем результаты нашей работы, гарантируем
                            регулярную
                            отчетность.
                        </li>
                        <li class="slider__item">
                            Мы не разбрасываемся деньгами наших клиентов, а относимся к ним как к собственным,
                            поэтому
                            заранее просчитываем приблизительный бюджет на рекламную кампанию. Выстраиваем
                            прозрачные
                            отношения с заказчиками и не скрываем результаты нашей работы, гарантируем
                            регулярную
                            отчетность.
                        </li>
                        <li class="slider__item">
                            Мы не разбрасываемся деньгами наших клиентов, а относимся к ним как к собственным,
                            поэтому
                            заранее просчитываем приблизительный бюджет на рекламную кампанию. Выстраиваем
                            прозрачные
                            отношения с заказчиками и не скрываем результаты нашей работы, гарантируем
                            регулярную
                            отчетность.
                        </li>
                    </ul>
                </div>
            </div>
        </section>
        <section class="how-we-analyze bg-light-gray">
            <div class="wrap">
                <h2 class="title wow bounceInRight" data-wow-duration="0.8s" data-wow-delay="0.3s">Как мы проводим
                    анализ
                </h2>
                <ul class="how-we-analyze__list">
                    <li class="how-we-analyze__item wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="0.3s">
                        Анализируем объявления на конкурентноспособность: насколько соответствует запросам,
                        достаточно ли конкретики, насколько выгодно УТП и т.д.
                    </li>
                    <li class="how-we-analyze__item wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.4s">
                        Оцениваем эффективность площадок размещения рекламы, делаем тщательный отбор
                    </li>
                    <li class="how-we-analyze__item wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="0.6s">
                        На основе полученных данных в системах аналитики сужаем трафик в точности до целевой
                        аудитории, что значительно увеличивает CTR рекламной кампании
                    </li>
                    <li class="how-we-analyze__item wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.7s">
                        Отслеживаем поведение посетителей на целевых страницах, даем рекомендации по улучшению
                        юзабилити сайта для увеличения конверсии
                    </li>
                    <li class="how-we-analyze__item wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay="0.9s">
                        Отслеживаем показатели ROI и CTR, увеличиваем их за счет постоянной работы над семантическим
                        ядром
                    </li>
                    <li class="how-we-analyze__item wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="1s">
                        Анализируем затраты на рекламу, находим эффективные решения для грамотного расхода
                        рекламного бюджета
                    </li>
                </ul>
            </div>
        </section>
        <section class="reviews">
            <div class="wrap">
                <h2 class="title wow bounceInRight" data-wow-duration="0.8s" data-wow-delay="0.3s">Отзывы наших клиентов
                </h2>
                <div class="reviews-slider__wrap wow fadeInUp" data-wow-duration="0.8s" data-wow-delay="0.3s">
                    <ul class="reviews-slider__list">
                        <li class="reviews-slider__item">
                            <a href="/img/review-img-1.jpg" data-fancybox="images">
                                <img src="/img/review-img-1.jpg" />
                            </a>
                        </li>
                        <li class="reviews-slider__item">
                            <a href="/img/review-img-2.jpg" data-fancybox="images">
                                <img src="/img/review-img-2.jpg" />
                            </a>
                        </li>
                        <li class="reviews-slider__item">
                            <a href="/img/review-img-3.jpeg" data-fancybox="images">
                                <img src="/img/review-img-3.jpeg" />
                            </a>
                        </li>
                        <li class="reviews-slider__item">
                            <a href="/img/review-img-4.jpg" data-fancybox="images">
                                <img src="/img/review-img-4.jpg" />
                            </a>
                        </li>
                        <li class="reviews-slider__item">
                            <a href="/img/review-img-5.jpg" data-fancybox="images">
                                <img src="/img/review-img-5.jpg" />
                            </a>
                        </li>
                        <li class="reviews-slider__item">
                            <a href="/img/review-img-6.jpeg" data-fancybox="images">
                                <img src="/img/review-img-6.jpeg" />
                            </a>
                        </li>
                        <li class="reviews-slider__item">
                            <a href="/img/review-img-7.png" data-fancybox="images">
                                <img src="/img/review-img-7.png" />
                            </a>
                        </li>
                        <li class="reviews-slider__item">
                            <a href="/img/review-img-8.jpg" data-fancybox="images">
                                <img src="/img/review-img-8.jpg" />
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </section>
        <section class="want-work">
            <div class="wrap">
                <h2 class="title wow bounceInRight" data-wow-duration="0.8s" data-wow-delay="0.3s">Хотите с нами
                    работать?
                </h2>
                <h4 class="subtitle wow fadeInUp" data-wow-duration="0.8s" data-wow-delay="0.3s">Оставьте свой
                    контактный телефон, и мы обязательно свяжемся с Вами в ближайшее
                    рабочее время</h4>
                <form  class="form contact-form" enctype="multipart/form-data">
                    <div class="">
                        <input class="wow fadeInUp" data-wow-duration="0.8s" data-wow-delay="0.3s" type="text" name="name"
                            placeholder="Ваше имя*" required>
                        <input class="wow fadeInUp" data-wow-duration="0.8s" data-wow-delay="0.5s" type="email" name="email"
                            placeholder="E-mail*" required>
                        <input class="wow fadeInUp" data-wow-duration="0.8s" data-wow-delay="0.7s" type="tel" name="phone"
                            placeholder="+7 (___) ___-__-__" id="phone">
                    </div>
                    <textarea class="wow fadeInUp" data-wow-duration="0.8s" data-wow-delay="0.9s" name="message"
                        placeholder="Ваш вопрос*" required></textarea>
                    <label for="file-upload" class="wow fadeInUp" data-wow-duration="0.8s" data-wow-delay="1.1s" style="cursor: pointer">
                        <input type="file" name="file" id="file-upload">
                        <span>Прикрепить файл</span>
                    </label>
                    <p>
                        <button class="wow fadeInUp" data-wow-duration="0.8s" data-wow-delay="1.3s">Отправить</button>
                    </p>
                    <h4 class="subtitle wow fadeInUp" data-wow-duration="0.8s" data-wow-delay="1.5s">
                        Отправляя форму, вы соглашаетесь с политикой обработки и использования
                        персональных данных</h4>
                </form>
            </div>
        </section>
    </main>
    <footer class="footer">
        <div class="wrap">
            <a href="/" class="logo wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.2s"><img
                    src="/img/logo.png" alt=""></a>
            <nav class="menu">
                <ul class="menu__list">
                    <li class="menu__item wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.3s"><a
                            href="#">Услуги</a></li>
                    <li class="menu__item wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.4s"><a
                            href="#">Работы</a></li>
                    <li class="menu__item wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.5s"><a
                            href="#">Отзывы</a></li>
                    <li class="menu__item wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.6s"><a
                            href="#">Контакты</a></li>
                </ul>
                <a href="#" class="drop-menu wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.7s">
                    <img src="/img/menu.png" alt="кнопка меню">
                </a>
            </nav>
            <div class="social__links">
                <a href="#" class="social__link wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.8s"><img
                        src="/img/facebook.png" alt="facebook"></a>
                <a href="#" class="social__link wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.9s"><img
                        src="/img/instagram.png" alt="instagram"></a>
                <a href="#" class="social__link wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="1s"><img
                        src="/img/twitter.png" alt="twitter"></a>
            </div>
            <a href="tel:+74232060353" class="phone wow fadeInRight" data-wow-duration="1.1s"
                data-wow-delay="0.3s">+7(423)<span>206 0353</span></a>
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- <script src="/optimo/templates/optimo/style/js/main.min.js"></script> -->
    <!-- <script src="/optimo/templates/optimo/style/js/main.js"></script> -->
    <script src="/optimo/templates/optimo/style/js/jquery.bxslider.js"></script>
    <script src="/optimo/templates/optimo/style/js/jquery.fancybox.js"></script>
    <script src="/optimo/templates/optimo/style/js/script.js"></script>
    <script src="/optimo/templates/optimo/style/js/jquery.maskedinput.js"></script>
    <script src="/optimo/templates/optimo/style/js/wow.min.js"></script>
    <script>
        $(window).on('load', function () {
            if ($(window).width() < 1201) {} else {
                new WOW().init();
            }
        })

        $(function () {
            $("#phone").mask("+7(999) 999-9999");
        });

        jQuery(document).ready(function () {
            jQuery('.slider__list').bxSlider({
                infiniteLoop: false,
            });
        });
        jQuery(document).ready(function () {
            jQuery('.reviews-slider__list').bxSlider({
                infiniteLoop: true,
                slideWidth: 260,
                slideMargin: 30,
                maxSlides: 4,
                minSlides: 1,
                moveSlides: 1,
            });
        });
    </script>
    <link rel="stylesheet" href="/optimo/templates/optimo/style/css/fonts.css">